# -*- coding: utf-8 -*-
"""Copia de Copia de Semana2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNFEd-dgdg64gUs8CsBtrBs7e_MCz0Nb
"""

numero1= int(input("Ingresa el primer numero: "))
numero2= int(input("Ingresa el segundo numero: "))

if numero1==numero2:
   print(f"Ambos numeros son iguales")
elif numero1>numero2: #si no se cumplio la anterior condicion evalue otro si u otra ocndicion
  print(f"{numero1} es mayor que {numero2}")
else:
 print(f"{numero2} es mayor que {numero1}")

numero1= int(input("Ingresa un numero: "))

if numero1 % 2 == 0:
   print(f"El numero {numero1} es par")
else:
  print(f"El numero {numero1} es impar")

edad= int(input("Ingresa tu edad: "))
if edad>=1 and edad <=12 :
  print(f"Tienes {edad} años , eres un niño. ")
elif edad >=13 and edad <=17 :
  print(f"Tienes {edad} años , eres un adolescente. ")
elif edad>=18 and edad <=64 :
  print(f"tienes {edad} años , eres un adulto. ")
else:
  print(f"tienes {edad} años, eres un adulto mayor. ")

nota= float(input("Ingresa tu nota: "))
if nota>=1.0 and nota<=1.9 :
  print(f"Tienes una nota de {nota} , y tu rendimiento es pesimo ")
elif nota>=2.0 and nota<=2.9 :
  print(f"Tienes una nota de {nota} , y tu rendimiento es malo ")
elif nota>=3.0 and nota<=3.9 :
  print(f"Tienes una nota de {nota} , y tu rendimiento es bueno ")
else:
  print(f"tienes una nota de {nota} , FELICITACIONES! tu rendimiento es excelente ")

numero= int(input("Ingrese un numero entre el 1 y el 10: "))
if numero>=1 and numero<=10 :
  print(f"el numero {numero} , Si esta entre el 1 y el 10")
else:
  print(f"el numero {numero} , No esta entre el 1 y el 10 ")

numero= int(input("Ingrese un numero: "))
if numero<0 or numero>100:
   print(f"el numero ingresado es negativo o mayor que 100 ")
else:
  print("el numero ingresado NO es ni negativo ni mayor que 100")

numero1= int(input("Ingrese el primer numero: "))
numero2= int(input("Ingrese el segundo numero: "))
operacion= input("Ingrese que operacion desea realizar (suma, resto, multiplicacion, división): ")
resultado = 0
if resultado == 'suma':
  resultado = numero1 + numero2
  print("El resultado es: {resultado}")